### ISSUE TITLE
Validator fails final page of all data feeds

### ISSUE THREAD

**Issue by thill-odi** [openactive/rpde-validator#25]
The validator appears to be broken, automatically failing the final page of all feeds apparently on the grounds that the data items are missing attributes (which they are, as by definition the final page doesn't have any items).

See for example:

* https://www.englandsquash.com/public/v1/sessions?afterTimestamp=24834&afterId=24475 
* https://opendata.leisurecloud.live/api/feeds/NottinghamCC-live-session-series?afterTimestamp=66790919&afterId=CRES00007249

**Comment by lukehesluke** [comment]
# Still happening?

To confirm that this is still the case, using https://validator.openactive.io/

## This passes (model) validation

```json
{
  "next": "https://acme-feed.com/feeds/scheduled-sessions?afterChangeNumber=1234",
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "items": [
    {
      "state": "deleted",
      "kind": "ScheduledSession",
      "id": "12345",
      "modified": 1235
    }
  ]
}
```

## This fails (model) validation

```json
{
  "next": "https://acme-feed.com/feeds/scheduled-sessions?afterChangeNumber=1234",
  "license": "https://creativecommons.org/licenses/by/4.0/",
  "items": []
}
```

# Impact

I'm not sure what prompted this issue in the first place, but it does seem that it could hamper a data publisher's ability to run automated validation on their feeds as part of CI, which should otherwise be encouraged

**Comment by lukehesluke** [comment]
I'm closing this issue as the Data Model Validator aspect has been raised separately and the only issue with RPDE Validator is a warning that no deleted items are detected, which I think is acceptable
